
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      APP_DB_URL: jdbc:postgresql://db:5432/appdb
      APP_DB_USER: postgres
      APP_DB_PASS: postgres
    ports:
      - "8080:8080"
    # No dev server inside container
    command: ["sh","-c","java -Dvaadin.productionMode=true -Duser.timezone=UTC -jar app.jar"]
volumes:
  dbdata:
