version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: budjeting
      POSTGRES_USER: budjet
      POSTGRES_PASSWORD: budjet
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/budjeting
      SPRING_DATASOURCE_USERNAME: budjet
      SPRING_DATASOURCE_PASSWORD: budjet
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
volumes:
  db_data:
