spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/budjeting
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
vaadin:
  productionMode: true
