
spring:
  datasource:
    url: ${APP_DB_URL:jdbc:postgresql://localhost:5432/appdb}
    username: ${APP_DB_USER:postgres}
    password: ${APP_DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  jackson:
    time-zone: UTC

server:
  port: ${PORT:8080}

logging:
  level:
    org.hibernate.SQL: warn

vaadin:
  launch-browser: false
